// WebSample/JSViewer_Angular_Core/JSViewer_Angular_Core.Client/src/app/report-viewer/report-viewer.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import { JSViewer, createViewer} from '@mescius/activereportsnet-viewer-ja';

@Component({
  selector: 'report-viewer',
  templateUrl: './report-viewer.component.html',
  styleUrls: [
      './report-viewer.component.css',
      '../../../node_modules/@mescius/activereportsnet-viewer-ja/dist/jsViewer.min.css'
  ],
  encapsulation: ViewEncapsulation.None,
})
export class ReportViewerComponent {
  private viewer: JSViewer | null = null;

  @Input() set reportId(reportId: string) {
      if (!this.viewer) {
          this.viewer = createViewer({
              element: '#viewerPlaceHolder'
          });
      }

      this.viewer.openReport(reportId);
  }
}

// WebSample/JSViewer_React_Hooks/JSViewer_React_Hooks.Client/src/reportViewer.tsx
import { useEffect, useRef } from 'react';

import { type JSViewer, createViewer } from '@mescius/activereportsnet-viewer-ja';
import "@mescius/activereportsnet-viewer-ja/esm/jsViewer.min.css";

type ViewerProps = {
  reportId: string
};

export function ReportViewer({reportId}: ViewerProps) {
  const viewerRef = useRef<JSViewer | undefined>(undefined);

  useEffect(() => {
    if(viewerRef.current === undefined){
      viewerRef.current = createViewer({
        element: "#viewerContainer",
      });
    }
  }, []);

  useEffect(() => {
    if (reportId && viewerRef.current) {
      viewerRef.current.openReport(reportId);
    }
  }, [reportId]);

  return <div className="main-container" id="viewerContainer" />;
}
